### ISSUE TITLE
Is there a way to get Container registry info?

### ISSUE THREAD

**Issue by vkolodrevskiy** [googleapis/java-artifact-registry#289]
Hello,

Is there a way to get Container registry info? I just need to get list of docker images inside one of the folders inside Container registry.

Trying to use [java-artifact-registry](https://github.com/googleapis/java-artifact-registry) module, but seems to be able to get info for artefict registry only.

**Comment by rogerthatdev** [comment]
Container Registry implements the Docker Registry API: https://cloud.google.com/container-registry/docs/reference/docker-api 

Also [here](https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr) is some information on transitioning from Container Registry to Artifact Registry, as recommended.
